### ISSUE TITLE
"Refresh published scheduled" is broken

### ISSUE THREAD

**Issue by aheritier** [nicmarti/cfp-devoxx#165]
The error is

```
[ERROR] [04/15/2019 11:44:27.736] [application-akka.actor.default-dispatcher-2] [akka://application/user/$a] key not found: ZXL-4420
java.util.NoSuchElementException: key not found: ZXL-4420
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at library.ZapActor$$anonfun$11.apply(ZapActor.scala:455)
	at library.ZapActor$$anonfun$11.apply(ZapActor.scala:452)
	at scala.collection.immutable.List.map(List.scala:277)
	at library.ZapActor.doCheckSchedules(ZapActor.scala:451)
	at library.ZapActor$$anonfun$receive$1.applyOrElse(ZapActor.scala:121)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at library.ZapActor.aroundReceive(ZapActor.scala:100)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[error] 09:44:42 [ForkJoinPool-5-worker-13] application:

! @7bgk40fae - Internal server error, for (GET) [/admin/refreshSchedules] ->

play.api.Application$$anon$1: Execution exception[[AskTimeoutException: Ask timed out on [Actor[akka://application/user/$a#2108946576]] after [15000 ms]]]
	at play.api.Application$class.handleError(Application.scala:296)
	at play.api.DefaultApplication.handleError(Application.scala:402)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205)
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.util.Failure.recover(Try.scala:215)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
	at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324)
Caused by: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://application/user/$a#2108946576]] after [15000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aheritier** [comment]
The problem was an incoherency with the talk `ZXL-4420` which was still in backup state instead of accepted. Fixing the status and republishing the agenda solved the issue
